### ISSUE TITLE
Question about the pair-wise loss

### ISSUE THREAD

**Issue by colorjam** [irfanICMLL/structure_knowledge_distillation#31]
Hi, thank you for your interesting work.
I'm curious about the \alpha in Eq.2. The definition of \alhpa is the connection range, however, in the `CriterionPairWiseforWholeFeatAfterPool` there is no parameter related to \alpha. Would you mind explain the implementation of \alpha in Eq2.?

**Comment by irfanICMLL** [comment]
It is a discussion about the pair-wise loss. The results show that keeping a fully connect range is the best choice considering the performance, and use a large \beta will help improve the results. We use a pooling operator for the \beta to achieve the best choice in our paper.

On P6 of our paper, we can get a conclusion from the table. "One can choose to use the local patch to decrease the number of the nodes, instead of decreasing the connection range for a better trade-off between efficiency and accuracy"
