### ISSUE TITLE
Pretrained student?

### ISSUE THREAD

**Issue by mbahri** [irfanICMLL/structure_knowledge_distillation#58]
The training script specifies
```
--student-pretrain-model-imgnet ./dataset/resnet18-imagenet.pth \
```

Would it be possible to get the weights please?

I've tried loading the pre-trained ResNet18 from torchvision but it didn't work because some kernels are 7x7 instead of 3x3.

I also tried loading http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet18-imagenet.pth, loading seems to work but then the dataloader threads crash with a segmentation fault.

I can train with a student from scratch, so it seems the crash is related to loading the pre-trained model.

Any help would be greatly appreciated.

**Comment by irfanICMLL** [comment]
I use this pre-trained weight.

https://cloudstor.aarnet.edu.au/plus/s/fNk3BUezIlJv0Y2

**Comment by BBBBchan** [comment]
> I use this pre-trained weight.
> 
> https://cloudstor.aarnet.edu.au/plus/s/fNk3BUezIlJv0Y2

This pre-trained weight you provide can not fit the student model in your code (I have checked out to d1ec858 branch). I follow the #44 and use [this](https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/mit_semseg/models/resnet.py) pre-trained weight. The final model achieves 0.715 MIOU at 39697 steps. Is this because I use the different pre-trained student model? If so, how can I fit this pre-trained weight into the code?
